[package]
name = "dylan/combatgame"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@^1.4.6"
Signal = "sleitnick/signal@1.0.1"
ProfileService = "brittonfischer/profileservice@2.1.5"
Promise = "evaera/promise@4.0.0"
Trove = "sleitnick/trove@0.4.0"
EnumList = "sleitnick/enum-list@2.0.0"
Component = "sleitnick/component@2.4.5"
Input = "sleitnick/input@1.3.3"